### ISSUE TITLE
A Blog Engine Based on GitHub Issue With the Power of Next.js ISR

### ISSUE THREAD

**Issue by djyde** [djyde/sairin#1]
---
path: introducing-sairin
---

![Desktop - 1 (1)](https://user-images.githubusercontent.com/914329/155258537-7989998a-931c-47f4-9d2c-5f6c21cc75df.png)

> TLDR: [Step by step guide](#step-by-step-guide)

## Background

Many people are using GitHub Issue for blogging. Because you can just create an issue and write some markdown to post some content. When you want to inject an image, just paste an image on the editor and it can be uploaded to GitHub. No need to worry about the static files hosting.

Some tools use GitHub API to generate a static blog. This is fine but when a post is updated, we need to redeploy the whole project (although we usually have automation to do this).

I came up with an idea that using Next.js to generate a blog, fetch blog posts from GitHub issues from a repository. But the problem is: if we put the GitHub API call on every blog post page request to fetch the issue content, it will reach the API rate limit soon. It doesn't scale.

Fortunately, Next.js has a special data fetching policy called [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), it means we can generate static pages first, and update them on demand.

For example, we can set the post page update in every 1 minutes by using `revalidate` in `getStaticProps`:

```js
export async function getStaticProps() {
  const res = await fetch('https://api.github.com/xxx')
  const posts = await res.json()

  return {
    props: {
      posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 1 minutes
    revalidate: 60, // In seconds
  }
}
```

It means that suppose we have 50 posts, every hour will call the API `3600s / 60 * 50 issues = 3000` times, which is under the 5000 request per hour rate limit.

The benefit of using GitHub issue as the content base over markdown files on project is GitHub issue comes with reaction and comments that we can show on the blog post (this feature is still working in progress).

## Step by step guide

Before creating a Sairin blog, you need to [generate a personal access token](https://github.com/settings/tokens/new) with the `repo` scope:

![image](https://user-images.githubusercontent.com/914329/155182611-2f71dc38-d0cd-4fd6-bf4f-6ca4019a8ddd.png)

Then click the deploy button below:

<a target="_blank" href="https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fdjyde%2Fsairin-starter&env=GITHUB_TOKEN&envDescription=GitHub%20personal%20access%20token&envLink=https%3A%2F%2Fgithub.com%2Fsettings%2Ftokens"><img src="https://vercel.com/button" alt="Deploy with Vercel"/></a>

This button will direct you to create a new project on Vercel based on Sairin template. 

![image](https://user-images.githubusercontent.com/914329/155183487-1fb76331-a188-430c-8bdc-f5392537e2b7.png)

Enter a project name and click `create`, then enter the personal access token you generated before and click `deploy`, it will begin to deploy your blog. 

After building you can open the repo that was created by Vercel on the dashboard, all your blog posts will be fetched on this repo:

![image](https://user-images.githubusercontent.com/914329/155017507-9b0045e3-bd86-4683-9d41-f3151d04cf41.png)

### Publish your first post 🚀

To publish a post, just create an issue on the repo. Notice that you need to add a frontmatter on the top of the content, to specify a permalink of your post, for example:

```yaml
---
path: introducing-sairin
---
```

![image](https://user-images.githubusercontent.com/914329/155018958-1c90e68a-49c4-40ea-9b0a-17791c619699.png)

Issues on the repo would not be published by default unless you add a label `published` to the issue:

![image](https://user-images.githubusercontent.com/914329/155019261-6cb51a62-d144-451d-8e45-852400e7e4bb.png)

Now, the first post should be published. You can go to the domain that Vercel gave to your project to see your blog post. No need to redeploy the project.

![image](https://user-images.githubusercontent.com/914329/155019524-5c8ce34c-29c9-4621-8bcb-eebcd4c48d98.png)

Read the full document on https://github.com/djyde/sairin

**Comment by whtiehack** [comment]
再接入评论, 文章详细再展示发表时间 最后修改时间 基本就很完美了

**Comment by djyde** [comment]
> 再接入评论, 文章详细再展示发表时间 最后修改时间 基本就很完美了

下一步就是展示评论和 reactions

**Comment by whtiehack** [comment]
评论感觉可以复用 [gitalk]( https://github.com/gitalk/gitalk ) ?

**Comment by hyoban** [comment]
是否可以不补充 path 的信息，比如默认按照 issue 的序号来作为链接

**Comment by diamantdev** [comment]
Wow, That is a awesome and incredible project ! 👍🏻

**Comment by ysoftaoglu** [comment]
Amazing project 🚀
