### ISSUE TITLE
Still show the hiding comment

### ISSUE THREAD

**Issue by ZhaoTim** [djyde/sairin#12]
I can hide some comment ：
<img width="970" alt="image" src="https://user-images.githubusercontent.com/30540533/157357017-d5ee98c9-9591-4f8a-a2ce-627c1224f31f.png">

However when I hide the comments, in my Blog, it still shows up.

**Comment by ZhaoTim** [comment]
Perhaps the hidden comment will exist with a property like `isHidden`

**Comment by djyde** [comment]
It seems that GitHub API didn't provide a field that indicates whether a comment is hidden.
